- name: Set authorized key took from file
  user: name=ubuntu
        generate_ssh_key=yes

- name: Add pub keys
  authorized_key: user=ubuntu
                  key="{{ lookup('file', item) }}"
  with_fileglob:
    - ./public_keys/*.pub