---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: cloud_optional
    image: ami-0edcec072887c2caa
# rename this key as neccessary
    key_name: aws_key
    region: ap-southeast-2
    rem_user: ubuntu
    count: 1

  tasks:
    - name: Create a security group
      ec2_group:
        name: "{{ security_group }}"
        description: The webservers security group
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launch the new EC2 Instance
      ec2:
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ key_name }}"
        count: "{{count}}"
      register: ec2

    - name: Add host for new instance
      add_host:
        hostname: "{{ item.public_dns_name }}"
        id: "{{ item.id }}"
      with_items: "{{ ec2.instances }}"


    - name: Wait for SSH to come up
      wait_for:
        host: "{{ elastic_ip }}"
        port: 22
        state: started

- name: Configure Server
  hosts: webserver
  become: True
  remote_user: ubuntu
  gather_facts: False
  tags: server-config
  roles:
    - init
